config/routes.rb
Rails.application.routes.draw do
  get '/' => 'howmuch#index'
  get 'howmuch/homepage' => 'howmuch#homepage'
  get 'howmuch/info' => 'howmuch#info'
  get 'howmuch/init' => 'howmuch#init'
  get 'howmuch/test' => 'howmuch#test'
  get 'howmuch/set' => 'howmuch#set#'
  get 'howmuch/card' => 'howmuch#card'
  get 'howmuch/option' => 'howmuch#option'
  post 'howmuch/result' => 'howmuch#result'
  get 'howmuch/result_show'
  get 'howmuch/card_test'
  

end

app/models/course.rb
class Course < ActiveRecord::Base
    
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/howmuch_controller.rb
require 'open-uri'

class HowmuchController < ApplicationController
  def index
  end
  
  def homepage
  end
  
  def info
  end
  
  def init
  end
  def test
  end
  
  def set
     @costs = params[:cost_set]
  end
  
  def card
    @show = Course.all
    
  end
  
  def option
    @getcost = @costs
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
def randomized_background_image
  images = ["/assets/background_0.jpg", "/assets/background_2.jpg", "/assets/background_1", "/assets/background_3", "/assets/background_4", "/assets/background_5", "/assets/background_6", "/assets/background_7", "/assets/background_8", "/assets/background_9", "/assets/background_10", "/assets/background_11", "/assets/background_12"]
  images[rand(images.size)]
end
end

app/helpers/howmuch_helper.rb
module HowmuchHelper
end

app/views/howmuch/card.html.erb
<html id="card_html" lang="en" xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <meta name="mobile-web-app-capable" content="yes">


    <title>How much</title>
    <!-- Latest compiled and minified CSS -->
<!--Bootstrap  CSS-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
      <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <%= stylesheet_link_tag "card.scss"%>
      <link rel="stylesheet" type="text/css" href="css/jquery.dynameter.css">
</head>


<body id="card_body">
    <section id="clubs" class="section">
        <div class="container">
            <header class="section_hearder">
                <h2 class="section_title">
                    <span class="section_category"> A recommended course </span>
                    Do you like the recommended course?
                </h2>
            </header>
            
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                   <a href="<%=howmuch_set_path%>">  <button  type="button" class="btn btn-default btn-lg" >
                       <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                       <!--onclick="goReplace('/howmuch/set')"-->
                      
                    </button>
                     </a>
      
                    <button onClick="history.go(0)" type="button" class="btn btn-default btn-lg" id="repeat">
                        <span class="glyphicon glyphicon-repeat" aria-hidden="true"></span>
                       
                    </button>
                </div>
    	    </div>
    	    
            <div class="cards row">
                <div class="col-md-6 col-md-offset-3">
                    <hr/>
                    <% @show.each do |x| %>
                        <div class="card-block">
                            <h2 class="card-title" id="course_name"><%=x.course_name %></h4>
                            <p class="card-info" ><b>1.<%=x.l_one%>원</b></p>
                            <p class="card-text"><%=x.c_one%></p>
                            <p class="card-info"><b>2.<%=x.l_two%>원</b></p>
                            <p class="card-text"><%=x.c_two%></p>
                            <p class="card-info"><b>3.<%=x.l_three%>원</b></p>
                            <p class="card-text"><%=x.c_three%></p>
                            <hr/>
                        </div>
                    <% end %>
                    
                    
                    
                    <%= @showsss %>
                </div>
            </div>
        </div>
    </section>
    
<!--Bootstrap CDN--!>
<!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/jquery.dynameter.js"></script>
    
    <script>
        $('.carousel.carousel-slider').carousel({fullWidth: true});
    </script>
                        
    
    <script> function goReplace(str) { location.replace(str); } </script>
</body> 
</html>

app/views/howmuch/homepage.html.erb
<html>
<head>
    <title>How much home</title>
    <!-- Background Image --!>
    <%= stylesheet_link_tag "homepage.scss"%>
</head>
<body>

  <div class="logo_half">
    <img src="../assets/logo_half.png" alt="harl logo image">
  </div>

  <div class="jumbotron">
    <p id="icon-x"><a href="/howmuch/init"><span class="glyphicon glyphicon-remove-circle"></span></a></p>
    <div class="container">
      <p id="baloon">'얼마면 돼?'가 궁금해?</p>
      <p id="baloon">'얼마면 돼?'는 <b>정해진 예산에서 즐길 수 있는
최대의 즐거움</b>을 찾 는 걸 도와주는 서비스야.</br>
사용법은 다음과 같아.</p>

    <iframe class="info_tab" src="/howmuch/info">
    </iframe>
    </div>
  </div>

<!--Bootstrap CDN--!>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/howmuch/index.html.erb
<html>
<head>
    <title>How much index</title>
    <!-- Latest compiled and minified CSS -->
<!--Bootstrap  CSS--!>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.0/angular.min.js"></script>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
      <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <%= stylesheet_link_tag "custom.scss"%>
      <link rel="stylesheet" href="../assets/stylesheets/custom.scss">
    
</head>
<body>
<!-- # Random Background Image --!>
<style type="text/css">
html {
    background: url(<%= randomized_background_image %>) no-repeat center center fixed; 
  }
</style>

<!-- JQuery CDN--!>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <div class="logo">
        <a href="howmuch/homepage"/> <img src="../assets/logo.png" onmouseover="this.src='../assets/logo2.png'" onmouseout="this.src='../assets/logo.png'" alt="logo image"> </a>
    </div>
    
    <div class="info">
        <a href="howmuch/homepage" class="button_Info">i</a>
    </div>
    

<!--Bootstrap CDN--!>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/howmuch/info.html.erb
<html>
<head>
    <title>How much Information</title>
    <!-- Backgroun Image --!>
    <%= stylesheet_link_tag "info_step.scss"%>
</head>
<body>
    <div class="info_step">
      <img src="../assets/step1.png" alt="step1_info">
      <img src="../assets/step2.png" alt="step2_info">
      <img src="../assets/step3.png" alt="step3_info">
    </div>


<!--Bootstrap CDN--!>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/howmuch/init.html.erb
<html>
<head>
    <title>How much</title>
    <!-- Latest compiled and minified CSS -->
<!--Bootstrap  CSS--!>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
      <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <%= stylesheet_link_tag "init.scss"%>
</head>
<body class="init_body">

  <div class="logo">
        <a href="<%=howmuch_set_path%>"/> <img src="../assets/logo.png" onmouseover="this.src='../assets/logo2.png'" onmouseout="this.src='../assets/logo.png'" alt="logo image"> </a>
  </div>
    
  <div class="info">
        <a href="/howmuch/homepage" class="button_Info">i</a>
  </div>
  <div class="init_container">
    <p id="baloon_chat1">안녕?</p>
    <p id="baloon_chat2">지금 주머니에 얼마나 있어?</p>
    <p id="baloon_chat3"><b>그 행복 · · · 얼마면 돼?</b></p>
  </div>
  
  <div class="info">
    <a href="<%=howmuch_homepage_path%>" class="button_Info">i</a>
  </div>
<!--Bootstrap CDN--!>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/howmuch/option.html.erb
<html>
<head>
    <title>How much home</title>
    <!-- Background Image --!>
    <%= stylesheet_link_tag "option.scss"%>
</head>
<body>

  <div class="jumbotron_option">
  <form action="/howmuch/result" method="post" >
    <p id="icon-x"><a href="/howmuch/set"><span class="glyphicon glyphicon-remove-circle"></span></a></p>
    <div class="container">
        <p id="baloon_q">언제야?</p>
        <p id="baloon_a" class="col-md-offset-3">
          <button class="button2">무관</button>
          <button class="button2">평일</button>
          <button class="button2">주말</button>
        </p>
        <p id="baloon_q">활동 장소는?</p>
        <p id="ballon_a" class="col-md-offset-3">
          <button class="button2">무관</button>
          <button class="button2">실내</button>
          <button class="button2">실외</button>
        </p>
    <button name="getcost" type="submit" class="button"> <b>전부 선택했다면</b>이 말풍선을 클릭해줘.</button>
    </div>
    </form>
  </div>
  
  var selector, elems, makeActive;
  
  selector = '.button button2';
  
  elems = document.querySelectorAll(selector);
  
  makeActive = function () {
      for (var i = 0; i < elems.length; i++)
          elems[i].classList.remove('active');
      
      this.classList.add('active');
  };
  
  for (var i = 0; i < elems.length; i++)
      elems[i].addEventListener('mousedown', makeActive);

<!--Bootstrap CDN--!>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/howmuch/set.html.erb
<html>
<head>
    <title>How much</title>
    <!-- Latest compiled and minified CSS -->
<!--Bootstrap  CSS--!>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
      <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <%= stylesheet_link_tag "set.scss"%>
      <link rel="stylesheet" type="text/css" href="css/jquery.dynameter.css">
      <script src="jquery-3.2.1.min.js"></script>
</head>
<body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <div class="set_cost">
    
        <input type="text" value="0" class="dial" data-angleOffset=90,
data-linecap=round>
            <script>
                $(function() {
                    $(".dial").knob({
                        'min':0,
                        'max':50000,
                        'step':500,
                        'angleOffset':30,
                        'angleArc':300,
                    });
                });
            </script>
        <a class="btn" href="/howmuch/option" role="button">click</a>
    </div>
    
    
<!--Bootstrap CDN--!>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script type="text/javascript" src="js/jquery.min.js"></script>
<script type="text/javascript" src="js/jquery.dynameter.js"></script>
</body>
</html>

app/views/howmuch/test.html.erb
<html>
<head>
    <title>How much</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
      <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <%= stylesheet_link_tag "test.scss"%>
</head>
<body>

    <div ani_type="bounce">
	날아올라
    </div>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!--CDN불러오는 주소 입력-->
  
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/js/materialize.min.js"></script>
    
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>